### ISSUE TITLE
Velocity / Delta Position Controller

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1126]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ X] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Given that a lot of robot research uses delta position control or velocity control, could you add an example policy for one of these? I know these can be built with a light wrapper around the existing policies, but it could be nice to standardize. This way, if I want to use a dataset collected with a Polymetis velocity controller, it is straightforward.

## Current Behavior

There is no velocity or delta position controller.

## Expected Behavior

env.step([1,0,0]) moves robot forward by some standard unit of measurement.

## Links to any relevant pastes or documents 

Please post links to any relevant documents that might contain any extra information.

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

**Comment by exhaustin** [comment]
Added to our list of planned features, although I cannot promise a delivery date.
In the meanwhile feel free to let me know if you have any issues creating a custom velocity controller.

**Comment by AlexanderKhazatsky** [comment]
Just an update, just adding a delta=True option to the update_desired_ee_pose(...) function would be sufficient :)

**Comment by exhaustin** [comment]
Update on this issue: We are implementing a joint velocity controller in the low-level controller space in #1222. A Cartesian controller might come later but that is also low priority for us.

Adding a delta argument to the impedance methods doesn't seem to do much because the user can already easily increment the desired pose themselves.

**Comment by 1heart** [comment]
@AlexanderKhazatsky please reopen this issue if the current workarounds don't suffice. Thanks!
