### ISSUE TITLE
Create SelfNode instead of PlayerNode for droidlet agents

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/fairo#1135]
## Type of Issue

Right now all droidlet agents create a `PlayerNode` to register themselves in memory, I propose we instead use `SelfNode` that is meant exactly for this purpose. Link [here](https://github.com/facebookresearch/fairo/blob/aa0ee72ed1af5e309833bd9abbe3768061dcdd67/droidlet/memory/memory_nodes.py#L571)

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

**Comment by aszlam** [comment]
closed in https://github.com/facebookresearch/fairo/pull/1200
