### ISSUE TITLE
[Polymetis] Update libfranka to 0.9.0

### ISSUE THREAD

**Issue by siddk** [facebookresearch/fairo#1140]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)

## Description

Hey folks, our Panda recently got updated to firmware 4.2.1 which is incompatible with the base `libfranka` version (0.8.0) that `polymetis` installs by default. We need to ideally be running `libfranka` 0.9.0 under the hood, just wanted to figure out how to make that happen!

 Seems like we just need to update the submodule at [https://github.com/facebookresearch/fairo/tree/main/polymetis/polymetis/src/clients/franka_panda_client/third_party](https://github.com/facebookresearch/fairo/tree/main/polymetis/polymetis/src/clients/franka_panda_client/third_party) to the latest version? 
 
 Should we just run an editable source install and make the change? Is there a way to make this more general for others working with various firmware version?

**Comment by exhaustin** [comment]
Libfranka has been bumped: #1151

**Comment by siddk** [comment]
@exhaustin - to be clear, has this merged commit already bumped the publicly available conda package as well?

**Comment by exhaustin** [comment]
> @exhaustin - to be clear, has this merged commit already bumped the publicly available conda package as well?

That is correct, all commits merged into `main` will be automatically uploaded to our channel on Anaconda Cloud.
