### ISSUE TITLE
Install Polymetis without `conda` for use with conda-incompatible libraries

### ISSUE THREAD

**Issue by wualbert** [facebookresearch/fairo#1181]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [X] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

It would be great if there is an option of installing Polymetis without using `conda`. This will enable usage with libraries that do not support `conda`, such as [Drake](https://drake.mit.edu/installation.html)

## Current Behavior

Currently, installing dependencies (in `environment.yml`) via `conda` seem to be the only way of setting up Polymetis. Please correct me if I am wrong. I tried installing the libraries in `environment.yml` by hand but couldn't get Polymetis to work.

**Comment by soumith** [comment]
`conda` allows `pip` installs. so, you can install drake into a `conda` environment

**Comment by wualbert** [comment]
Unfortunately that does not work. Drake does not support Python environments supplied by Anaconda. From Drake's website:
>Drake does not support the Python environment supplied by Anaconda. Before installing or using Drake, please conda deactivate (repeatedly, until even the conda base environment has been deactivated) such that none of the paths reported which -a python python3 refer to conda.

I did try installing drake into a conda environment and it throws erros at runtime.

**Comment by soumith** [comment]
okay, reading Drake's page, it looks like they build wheels that are extremely brittle. They literally only work in `Ubuntu 20.04 LTS (Focal Fossa) | GCC 9.3`.

Making "correct wheels" for Polymetis might also break in this environment, because pip manywheel spec has a docker image that's based on CentOS.

Did you pressure the Drake devs to fix their packaging?

**Comment by 1heart** [comment]
@wualbert, have you tried compiling Polymetis from source under the same environment that Drake requires? Ubuntu20/GCC9 should be fine. Just requires the packages from [environment.yml](https://github.com/facebookresearch/fairo/blob/main/polymetis/polymetis/environment.yml), which you can probably get from your package manager if not from conda.

**Comment by wualbert** [comment]
Thanks for the inputs!

@soumith I'm not sure what you mean by "fix packaging". Their wheel works fine in the prescribed environment, and that's probably among the more popular setup anyways.

@1heart from what I understand, compiling Polymetis from source in a `conda`-supplied environment wouldn't make sense as Polymetis will still end up being installed in a conda-based python environment. I did try going through the packages from `environment.yml` by hand, and I ran into a bunch of issues. For instance using the specified Protobuf (3.18.1) and GRPC (1.41.1) yields the following error when compiling Polymetis
```
This file was generated by a newer version of protoc
```

I am not aware of a way to use `environment.yml` directly with a non-`conda` package manager. That's why I was asking if there's an alternative way to install Polymetis.

**Comment by wualbert** [comment]
@exhaustin can confirm that using non-conda versions of the packages is virtually impossible. 

For my application, I got away with using Polymetis (installed via conda) on the NUC and Drake (installed via pip) on the main machine. I set up the two to talk through ZMQ.

**Comment by exhaustin** [comment]
Awesome, glad you found a solution.
Closing this issue for now, feel free to reopen if you run into more installation issues.
