### ISSUE TITLE
Cartesian Impedance Controller FREQUENTLY Dies

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1190]
## Type of Issue

Select the type of issue:
- [X ] Bug report (to report a bug)

## Description
I'm not sure if its the case for others, but when running the impedance controller for a prolonged period of time (~30 seconds), it randomly and frequently dies out after around 10 seconds or less.

## Current Behavior

Even though I have a line calling robot.start_cartesian_impedance(), it works for a few seconds, and then eventually throughs an error saying I have to call robot.start_cartesian_impedance() before using impedance control.

## Expected Behavior

I expected that once I call robot.start_cartesian_impedance(), it should continue working for quite a while

## Steps to reproduce

Run the impedance controller for around 30 seconds.

**Comment by AlexanderKhazatsky** [comment]
It looks like it doesn't always have to do with time ran. When using the example script for cartesian control, maybe 1 out of every 5 runs errors for this reason

**Comment by AlexanderKhazatsky** [comment]
`Warning: Failed to load 'libtorchscript_pinocchio.so' from CONDA_PREFIX, loading from default build directory instead: '/home/khazatsky/code/fairo/polymetis/polymetis/build/torch_isolation/libtorchscript_pinocchio.so'
Warning: Failed to load 'libtorchrot.so' from CONDA_PREFIX, loading from default build directory instead: '/home/khazatsky/code/fairo/polymetis/polymetis/build/torch_isolation/libtorchrot.so'
Performing Cartesian impedance control...
Unable to update desired EE pose. Use 'start_cartesian_impedance' to start a Cartesian impedance controller.
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    robot.update_desired_ee_pose(position=ee_pos)
  File "/home/khazatsky/code/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 587, in update_desired_ee_pose
    raise e
  File "/home/khazatsky/code/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 582, in update_desired_ee_pose
    update_idx = self.update_current_policy(param_dict)
  File "/home/khazatsky/code/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 238, in update_current_policy
    raise grpc.RpcError(f"POLYMETIS SERVER ERROR --\n{e.details()}") from None
grpc.RpcError: POLYMETIS SERVER ERROR --
Tried to perform a controller update with no controller running.
`

**Comment by exhaustin** [comment]
Apologies for these issues, I know how annoying they can be.
We have been experiencing this performance issue a lot over the past, which usually goes away on this particular NUC spec after disabling CPU scaling.
 If that doesn't work for you, providing the diagnosis data from the tests described in the troubleshooting section will help us in pinpointing the source of the problem you are experiencing.

**Comment by AlexanderKhazatsky** [comment]
I disabled CPU scaling, and I'm still having the same issues :(

I'll look into the diagnostics stuff, thank you so much for all your help.

**Comment by AlexanderKhazatsky** [comment]
Alright, here's the diagnostics. I have tried with real kernel 5.11 (which made my NUC very slow to interact with) and real kernel 5.9.1 (which doesn't have this issue). I have had the same results with both, with and without disabling cpu scaling.

Libfranka Communication test: Average Success Rate of 97%
End to End Test: Joint PD: 0.2501/ 0.0280 / 0.7005 / 0.1465 / 0.00%, Cartesian PD: 0.3694/ 0.0373 / 1.0933 / 0.1239 / 0.00%

**Comment by AlexanderKhazatsky** [comment]
Here is the server error I get:

[2022-06-03 18:20:17.631] [info] Loaded new controller.
[2022-06-03 18:20:17.895] [error] Robot is unable to be controlled: libfranka: Move command aborted: motion aborted by reflex! ["communication_constraints_violation"]
control_command_success_rate: 0.46
[2022-06-03 18:20:17.895] [warning] Performing automatic error recovery. This calls franka::Robot::automaticErrorRecovery, which is equivalent to pressing and releasing the external activation device.
[2022-06-03 18:20:17.895] [warning] Automatic error recovery attempt 1/3...
[2022-06-03 18:20:18.897] [warning] Robot operation recovered.
[2022-06-03 18:20:18.900] [warning] Interrupted control update greater than threshold of 1000000000 ns. Reverting to default controller...
[2022-06-03 18:20:18.900] [info] Terminating custom controller, switching to default controller.
[2022-06-03 18:20:18.931] [warning] Tried to perform a controller update with no controller running.

**Comment by AlexanderKhazatsky** [comment]
I have talked with someone else who just started using Polymetis, and they have the same exact issue. I think it might be very prevalent.

**Comment by exhaustin** [comment]
Looks like your End to End Test results looks okay, although a bit on the slower side.
This exact issue can happen whenever the CPU performance isn't sufficient, but reasons for that can vary which make it very hard to debug. I don't think I will be able to help much in the immediate sense, you will need to look into various ways to improve CPU performance of your machine or to get a better machine. Suggestions I have is to look for and terminate background processes that are taking up resources, and maybe ensuring that the CPU is using the "performance" governor. Overclocking might also be an option.

Some architectural changes that will improve performance across the board is being planned, although I cannot guarantee a delivery date for now.

**Comment by AlexanderKhazatsky** [comment]
One thought about this - I’m running both the server and the controller (the example impedance script) on the same NUC (62g RAM, 8 CPUs which are i7 @ 2.8 GHz). Could this be the issue? Is it possible this will go away if I send commands from a different machine?

**Comment by AlexanderKhazatsky** [comment]
Also if it helps, the joint impedance control didnt really die. It's only the cartesian impedance control.

**Comment by exhaustin** [comment]
Running the script on a different machine *may* help, but I expect the benefits are minimal as the script does not take up a lot of resources. Also, I am able to run my scripts on the NUC without any problems on my setup.

Another thought, have you tried running the network tests [here](https://frankaemika.github.io/docs/troubleshooting.html#network-bandwidth-delay-and-jitter-test)? It might be the case where your machine is fast enough but your network connection to the robot isn't.

**Comment by AlexanderKhazatsky** [comment]
I’ve tried them. The robot is connected through a direct wire to the NUC and so the connection definitely seems fast enough.

**Comment by AlexanderKhazatsky** [comment]
Out of curiosity, are the spec's of your NUC comparable to mine? I'm completely at a loss for how I'm having these issues but no one else is. Is it also possible that upgrading to lib Franka 0.9.0 could help? I'm guessing not since you all have been using 0.8.0 it seems.

**Comment by exhaustin** [comment]
For reference, here are the specs for my NUC which is even older than the current batch we purchased at bulk for testing.
```
~/ cpuinfo
Python Version: 3.8.13.final.0 (64 bit)
Cpuinfo Version: 8.0.0
Vendor ID Raw: GenuineIntel
Hardware Raw:
Brand Raw: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
Hz Advertised Friendly: 1.1000 GHz
Hz Actual Friendly: 3.3000 GHz
Hz Advertised: (1100000000, 0)
Hz Actual: (3300001000, 0)
Arch: X86_64
Bits: 64
Count: 12
Arch String Raw: x86_64
L1 Data Cache Size: 32768
L1 Instruction Cache Size: 32768
L2 Cache Size: 262144
L2 Cache Line Size: 256
L2 Cache Associativity: 6
L3 Cache Size: 12582912
Stepping:
Model: 166
Family: 6
Processor Type:
Flags: 3dnowprefetch, abm, acpi, adx, aes, aperfmperf, apic, arat, arch_capabilities, arch_perfmon, art, avx, avx2, bmi1, bmi2, bts, clflush, clflushopt, cmov, constant_tsc, cpuid, cpuid_fault, cx16, cx8, de, ds_cpl, dtes64, dtherm, dts, epb, ept, ept_ad, erms, est, f16c, flexpriority, flush_l1d, fma, fpu, fsgsbase, fxsr, ht, hwp, hwp_act_window, hwp_epp, hwp_notify, ibpb, ibrs, ibrs_enhanced, ida, intel_pt, invpcid, invpcid_single, lahf_lm, lm, mca, mce, md_clear, mmx, monitor, movbe, mpx, msr, mtrr, nonstop_tsc, nopl, nx, osxsave, pae, pat, pbe, pcid, pclmulqdq, pdcm, pdpe1gb, pebs, pge, pln, pni, popcnt, pse, pse36, pts, rdrand, rdrnd, rdseed, rdtscp, rep_good, sdbg, sep, sgx, smap, smep, ss, ssbd, sse, sse2, sse4_1, sse4_2, ssse3, stibp, syscall, tm, tm2, tpr_shadow, tsc, tsc_adjust, tsc_deadline_timer, tscdeadline, vme, vmx, vnmi, vpid, x2apic, xgetbv1, xsave, xsavec, xsaveopt, xsaves, xtopology, xtpr
```

```
~/ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               166
Model name:          Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
Stepping:            0
CPU MHz:             3299.997
CPU max MHz:         4700.0000
CPU min MHz:         400.0000
BogoMIPS:            3199.92
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            12288K
NUMA node0 CPU(s):   0-11
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
```

**Comment by AlexanderKhazatsky** [comment]
Do you guys notice any difference in performance between libfranka versions?

**Comment by exhaustin** [comment]
We haven't noticed any, although we did not run any benchmarks to confirm that. Nevertheless, Cartesian impedance controllers work well on both versions for us.

**Comment by AlexanderKhazatsky** [comment]
I have an interesting update! I have resolved the issue by using Ubuntu 18 and a specific version from the conda installed polymetis. Below is my experience summary:


Polymetis installed from source (Ubuntu 18):
- Neither simulated or read robot worked

Polymetis installed from source (Ubuntu 20):
- Simulated robot worked
- Real robot worked with errors (communication errors there, and killed script)

Polymetis installed from Conda (Ubuntu 18):
- Simulated robot didn't work
- Real robot worked entirely (communication errors there, didn't kill script)

——————

I don’t think these results make it clear whether the difference is Ubuntu 18 vs 20 or installing from conda vs building it from source. Either way, it would be extremely helpful if you guys could look into this, given that our lab would like to be able to keep using the most up to date version of polymetis. Im happy to help in this process.

On a side note, the Polymetis support for Ubuntu 18 seems to have deteriorated, and we ran into significantly more problems setting it up than on Ubuntu 20.

**Comment by exhaustin** [comment]
The support we've been providing should not differ between different Ubuntu releases, and we even have automated tests on both Ubuntu 18 and 20 to assure things are working for both. 

As I mentioned, system performance is affected by a lot of issues, which could come from any step within the setup and not just the difference in the Ubuntu version. It is quite hard for me to look into exactly why only certain configurations work for you as I cannot reproduce any of the problems that you are experiencing on my side as of now. However, I will be pushing for general performance improvements as long as there are people experiencing these issues.

I am curious as to why simulated robots would not work in any situation, though. Can you provide the error messages you are seeing?

**Comment by 1heart** [comment]
To add onto @exhaustin's comment: you can check the exact Dockerfiles for [Ubuntu 18](https://github.com/facebookresearch/fairo/blob/main/polymetis/docker/ubuntu18/Dockerfile) and [Ubuntu 20](https://github.com/facebookresearch/fairo/blob/main/polymetis/docker/ubuntu20/Dockerfile), as well as the [tests we run for both](https://github.com/facebookresearch/fairo/blob/main/.circleci/config.yml#L18). Is your environment different?

**Comment by AlexanderKhazatsky** [comment]
Sorry for the late reply, here's the error I'm seeing:

`Traceback (most recent call last):
  File "/home/sasha/anaconda3/envs/polymetis/lib/python3.8/site-packages/hydra/_internal/utils.py", line 529, in _locate
    module = import_module(mod)
  File "/home/sasha/anaconda3/envs/polymetis/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1011, in _gcd_import
  File "<frozen importlib._bootstrap>", line 950, in _sanity_check
ValueError: Empty module name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sasha/anaconda3/envs/polymetis/lib/python3.8/site-packages/hydra/utils.py", line 61, in call
    type_or_callable = _locate(cls)
  File "/home/sasha/anaconda3/envs/polymetis/lib/python3.8/site-packages/hydra/_internal/utils.py", line 532, in _locate
    raise ImportError(f"Error loading module '{path}'") from e
ImportError: Error loading module 'polysim.grpc_sim_client.GrpcSimulationClient'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sasha/anaconda3/envs/polymetis/bin/launch_robot.py", line 89, in main
    client = hydra.utils.instantiate(cfg.robot_client)
  File "/home/sasha/anaconda3/envs/polymetis/lib/python3.8/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'polysim.grpc_sim_client.GrpcSimulationClient' : Error loading module 'polysim.grpc_sim_client.GrpcSimulationClient'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2022-06-13 18:46:34,178][__main__][INFO] - Killing subprocess with pid 12066, pgid 12066...
`

**Comment by 1heart** [comment]
@AlexanderKhazatsky please reopen this issue if you're still having problems with the original issue, or open a new issue for the PyBullet / OpenGL issues.

**Comment by paarthshah-tri** [comment]
Just wanted to leave a comment about having really similar issues here. Specifically, joint control seems to work well (albeit on the slower side), but cartesian impedance fails almost immediately. Similarily, I'm running both the server and the commands on the NUC (and am in the process of moving the 'command' files to an off-board PC to see if this helps).

**Comment by exhaustin** [comment]
The latency benchmark tests the end-to-end latency of the process of sending the states to the server, inferencing the controller in the server, and getting the output action from the server. So bad timings can be the result of either slow processing power or internet latency (or both).
As mentioned above, the internet latency can be tested with the libfranka communication test.
If the issue is processing power, try disabling the CPU scaling if you haven't yet, and consider getting a more powerful machine if all fails.

**Comment by paarthshah-tri** [comment]
I forgot to turn on Release mode when building. This fixed the issues I had been having. Might be worth adding to the docs at some point though!

`-DCMAKE_BUILD_TYPE=Release`

**Comment by AlexanderKhazatsky** [comment]
Can someone from Polymetis investigate this? I'm still having this issue still and would love a solution :)

**Comment by paarthshah-tri** [comment]
Are you building from source? If not, this is most likely not the problem. I suspect (I actually haven't checked this) but building using the conda scripts should probably build things from source automatically?

@AlexanderKhazatsky The above flag should be added to the CMake command if you're building it from source (https://facebookresearch.github.io/fairo/polymetis/installation.html#for-advanced-users-developers)

Specifically, the command should be something like:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_FRANKA=[OFF/ON] -DBUILD_TESTS=[OFF/ON] -DBUILD_DOCS=[OFF/ON]`

If you're still having this problem it's worth exploring building from source?

**Comment by mohanksriram** [comment]
> Are you building from source? If not, this is most likely not the problem. I suspect (I actually haven't checked this) but building using the conda scripts should probably build things from source automatically?
> 
> @AlexanderKhazatsky The above flag should be added to the CMake command if you're building it from source (https://facebookresearch.github.io/fairo/polymetis/installation.html#for-advanced-users-developers)
> 
> Specifically, the command should be something like:
> 
> `cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_FRANKA=[OFF/ON] -DBUILD_TESTS=[OFF/ON] -DBUILD_DOCS=[OFF/ON]`
> 
> If you're still having this problem it's worth exploring building from source?

I had the exact same problem. Changing the build type to release (on the polymetis server side) fixed the communication_constraints_violations error for me. (I'm building polymetis from source)

**Comment by 1heart** [comment]
Sorry about that and thanks for catching this -- at some point Release was the default mode (and still is in the conda-built packages), but the default was changed for standardization / debugging purposes. I updated the docs in #1323 to reflect this.

**Comment by HaoLiRobo** [comment]
Hi, @exhaustin, I also met the same issue, the cartesian control immediately dies or dies after I run some command to give it a cartesian goal position. Could you tell me what is the model of your NUC? Is it NUC TNK v5 or v7? I'm using a very old one (a NUC 7 i5)

Also, my current FCI version is 4.0.4, which version of polymetis do you recommend me using? I tried a few versions from 636 to 1065, and only 1065 didn't give me the following error. But 1065 has the problem of cartesian control dying. I'm a little bit lost now and don't know how to make the polymetis works.

> subprocess.CalledProcessError: Command '['sudo', 'env', '"PATH=$PATH"', '/home/haoli/anaconda3/envs/polymetis/bin/franka_panda_client', '/tmp/tmpi609pzpb']' died with <Signals.SIGABRT: 6>.

**Comment by exhaustin** [comment]
From my experience i5 CPUs in general are not powerful enough to keep up with the real time control loop, so switching to an i7 would definitely help. We've had success getting it to work on i7 NUCs from NUC 7 throughout NUC 10.

Nevertheless, it would help if you can go through our [troubleshooting section](https://facebookresearch.github.io/fairo/polymetis/troubleshooting.html) to ensure that you are getting the most performance out of your CPU and pinpoint the exact problem.

The latest version of Polymetis should give the most bug-free and stable performance. Can you upgrade your FCI to the latest version (4.2.0)? It can be done quite easily through Franka World. If not you might need to build Polymetis from source to use a particular version of libfranka that works with your version of the FCI.l
