### ISSUE TITLE
Libfranka Update Issues

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1191]
## Type of Issue

Select the type of issue:
- [ X] Bug report (to report a bug)

## Description

The recent update to handle to new libfranka software ruins compatibility for older franka software versions. We were only able to get it working with an older commit now. It could be beneficial to have some sort of backwards compatibility :)

## Current Behavior

Server fails to run correctly when paired with an older lib Franka version

## Steps to reproduce

Use an older libfranka version and try the most recent Polymetis code.

**Comment by AlexanderKhazatsky** [comment]
I think they are aware of the issue

**Comment by AlexanderKhazatsky** [comment]
I believe that you cannot simply swap the lib Franka when building from source. the build procedure errors when using a different lib Franka procedure. the only method that works is pulling a commit before they updated the lib Franka stuff

**Comment by exhaustin** [comment]
I am unable to repro your issue as libfranka builds and runs successfully with version 0.8.0 on my machine. The build procedure also should not have any assumptions regarding the version of libfranka.
I would do the following things:
- Check that correct versions of libfranka submodules are being checked out (with `--recurse-submodules` when checking out the desired libfranka version)
- Ensure a clean rebuild by removing the `build` folder
- Make sure `-DBUILD_FRANKA=ON` when building Polymetis

**Comment by AlexanderKhazatsky** [comment]
Okay, I tried with the most recent code and didnt run into this issue. It does however look that the current lib Franka building procedure fails to make the communication_test on my end. Are you guys having this issue on your end?

**Comment by exhaustin** [comment]
No we don't have this issue on our end. This should be related to #1190 so let's continue our discussion there.
