### ISSUE TITLE
GripperInterface sometimes breaks when using multiprocessing

### ISSUE THREAD

**Issue by raunaqbhirangi** [facebookresearch/fairo#1273]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

When running a background process using multiprocessing.Process, GripperInterface sometimes errors out. The gripper server must then be reset before it starts working again.

## Current Behavior

Error: 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File ".../lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File ".../lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".../lib/python3.8/site-packages/polymetis/gripper_interface.py", line 41, in _command_executor
    command(msg)
  File ".../lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File ".../lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Unexpected error in RPC handling"
        debug_error_string = "{"created":"@1657229675.771933655","description":"Error received from peer ipv4:172.16.0.1:50052","file":"src/core/lib/surface/call.cc","file_line":952,"grpc_message":"Unexpected error in RPC handling","grpc_status":2}"
```
## Expected Behavior

GripperInterface works does not crash when using multiprocessing.Process for a background process. 

## Steps to reproduce

```
import time
from polymetis import GripperInterface
from multiprocessing import Process, Event

class DummyProcess(Process):
    def __init__(self):
        super(DummyProcess, self).__init__()
        self._event_quit_request = Event()

    def join(self):
        self._event_quit_request.set()

    def run(self):
        while not self._event_quit_request.is_set():
            time.sleep(0.1)

if __name__ == '__main__':
    proc = DummyProcess()

    proc.start()
    gripper = GripperInterface(ip_address='172.16.0.1')

    pos_list = [0.04, 0.06]

    for i in range(5):
        gripper.goto(width=pos_list[i % 2], speed=5.0, force=0.0)
    
    proc.join()
```

**Comment by exhaustin** [comment]
Does the GripperInterface work normally without the async processes?
It seems like you should be running the Franka gripper server with `launch_gripper.py gripper=franka_hand` on the NUC connected to the robot. However, if the above is true, the `ip_address` field should be the ip of the server (which should be running on the NUC), not the ip address of the robot.

**Comment by exhaustin** [comment]
Hello feel free to disregard my previous comment. I found `172.16.0.1` to work as the IP of the NUC on my side too.

Update on reproducing: I was unable to reproduce the error by running the above script multiple times, with both Franka grippers and Robotiq grippers. 

#1279 will make errors on the gripper server more verbose. If you are building Polymetis from source locally, feel free to checkout the branch and try to repro the problem again to see if the error messages are more informative. If not, I will let you know when a new conda package with this feature is released so you can update to it.

**Comment by 1heart** [comment]
Please reopen if there's more information in the error message for reproducing -- thanks.

**Comment by raunaqbhirangi** [comment]
Still unsure what caused the error, but reinstalling and upgrading polymetis fixed the error.
