### ISSUE TITLE
[Polymetis] Error running the server and robot client (simulation)

### ISSUE THREAD

**Issue by mohanksriram** [facebookresearch/fairo#1278]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

I built polymetis from source following the instructions [here](https://facebookresearch.github.io/fairo/polymetis/installation.html)
I followed the usage instructions [here](url) to launch robot in simulation mode.

## Current Behavior
But I get the following error:
![image](https://user-images.githubusercontent.com/22681121/178540355-c44b8258-c0f9-4d7f-ae75-18132616c4ba.png)

## Steps to reproduce
Included in the description

**Comment by 1heart** [comment]
It looks like something went wrong during compilation. Can you ensure the versions in your conda environment exactly match those specified in [environment.yml](https://github.com/facebookresearch/fairo/blob/main/polymetis/polymetis/environment.yml) and then do a clean build?

**Comment by mohanksriram** [comment]
There was no version mismatch. Clean build from source after system restart helped.
