### ISSUE TITLE
[Polymetis] Building Polymetis From Source

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1338]
When building from source, during the lib franka building part, you get permission errors. Here's what my terminal outputs:

Submodule 'droidlet/lowlevel/minecraft/client/lib/rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path '../../../../../../../droidlet/lowlevel/minecraft/client/lib/rapidjson'
Submodule 'droidlet/lowlevel/minecraft/client/pybind11' (https://github.com/pybind/pybind11.git) registered for path '../../../../../../../droidlet/lowlevel/minecraft/client/pybind11'
Submodule 'droidlet/lowlevel/minecraft/logging/lib/argparse' (https://github.com/jonathathan/argparse.git) registered for path '../../../../../../../droidlet/lowlevel/minecraft/logging/lib/argparse'
Submodule 'droidlet/lowlevel/minecraft/server/cuberite' (https://github.com/cuberite/cuberite.git) registered for path '../../../../../../../droidlet/lowlevel/minecraft/server/cuberite'
Submodule 'droidlet/lowlevel/minecraft/server/cuberite_plugins/lib/lua-struct' (https://github.com/iryont/lua-struct.git) registered for path '../../../../../../../droidlet/lowlevel/minecraft/server/cuberite_plugins/lib/lua-struct'
Submodule 'perception/sandbox/polygrasp/third_party/UnseenObjectClustering' (git@github.com:1heart/UnseenObjectClustering.git) registered for path '../../../../../../../perception/sandbox/polygrasp/third_party/UnseenObjectClustering'
Submodule 'perception/sandbox/polygrasp/third_party/graspnet-baseline' (git@github.com:1heart/graspnet-baseline.git) registered for path '../../../../../../../perception/sandbox/polygrasp/third_party/graspnet-baseline'
Submodule 'polymetis/polymetis/python/polymetis/robot_drivers/psyonic_gripper/ability-hand-api' (git@github.com:1heart/ability-hand-api.git) registered for path '../../../../../python/polymetis/robot_drivers/psyonic_gripper/ability-hand-api'
Submodule 'polymetis/polymetis/src/clients/franka_panda_client/third_party/libfranka' (https://github.com/frankaemika/libfranka.git) registered for path './'
Submodule 'polymetis/polymetis/tests/cpp/fake_clock' (https://github.com/korfuri/fake_clock) registered for path '../../../../../tests/cpp/fake_clock'
Cloning into '/home/sasha/fairo/droidlet/lowlevel/minecraft/client/lib/rapidjson'...
Cloning into '/home/sasha/fairo/droidlet/lowlevel/minecraft/client/pybind11'...
Cloning into '/home/sasha/fairo/droidlet/lowlevel/minecraft/logging/lib/argparse'...
Cloning into '/home/sasha/fairo/droidlet/lowlevel/minecraft/server/cuberite'...
Cloning into '/home/sasha/fairo/droidlet/lowlevel/minecraft/server/cuberite_plugins/lib/lua-struct'...
Cloning into '/home/sasha/fairo/perception/sandbox/polygrasp/third_party/UnseenObjectClustering'...
Warning: Permanently added the ECDSA host key for IP address '192.30.255.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:1heart/UnseenObjectClustering.git' into submodule path '/home/sasha/fairo/perception/sandbox/polygrasp/third_party/UnseenObjectClustering' failed
Failed to clone 'perception/sandbox/polygrasp/third_party/UnseenObjectClustering'. Retry scheduled
Cloning into '/home/sasha/fairo/perception/sandbox/polygrasp/third_party/graspnet-baseline'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:1heart/graspnet-baseline.git' into submodule path '/home/sasha/fairo/perception/sandbox/polygrasp/third_party/graspnet-baseline' failed
Failed to clone 'perception/sandbox/polygrasp/third_party/graspnet-baseline'. Retry scheduled
Cloning into '/home/sasha/fairo/polymetis/polymetis/python/polymetis/robot_drivers/psyonic_gripper/ability-hand-api'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:1heart/ability-hand-api.git' into submodule path '/home/sasha/fairo/polymetis/polymetis/python/polymetis/robot_drivers/psyonic_gripper/ability-hand-api' failed
Failed to clone 'polymetis/polymetis/python/polymetis/robot_drivers/psyonic_gripper/ability-hand-api'. Retry scheduled
Cloning into '/home/sasha/fairo/polymetis/polymetis/src/clients/franka_panda_client/third_party/libfranka'...
Cloning into '/home/sasha/fairo/polymetis/polymetis/tests/cpp/fake_clock'...
Cloning into '/home/sasha/fairo/perception/sandbox/polygrasp/third_party/UnseenObjectClustering'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:1heart/UnseenObjectClustering.git' into submodule path '/home/sasha/fairo/perception/sandbox/polygrasp/third_party/UnseenObjectClustering' failed
Failed to clone 'perception/sandbox/polygrasp/third_party/UnseenObjectClustering' a second time, aborting
/home/sasha/fairo/polymetis
Building libfranka at /home/sasha/fairo/polymetis/polymetis/src/clients/franka_panda_client/third_party/libfranka/build
CMake Warning:
  Ignoring extra path from command line:

   ".."

CMake Error: The source directory "/home/sasha/fairo/polymetis/polymetis/src/clients/franka_panda_client/third_party/libfranka" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
/home/sasha/fairo/polymetis

**Comment by 1heart** [comment]
Does git cloning of [libfranka](https://github.com/frankaemika/libfranka) (or any repo) work? It looks like you're just not using SSH keys for git.

**Comment by exhaustin** [comment]
Closing issue, please reopen if the problem persists.

**Comment by AlexanderKhazatsky** [comment]
Yes, so sorry I had just never seen this before and thought it was a private repo or something. My bad!
