### ISSUE TITLE
Franka Command To Lock / Unlock Joints

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1347]
## Type of Issue

Select the type of issue:
- [X] Feature request (to request an additional feature)
## Description

I'm doing a data collection project across multiple homes and we would really like to not have to bring a monitor everywhere. Currently, the only thing we need it for is to unlock the Franka joints after turning it on. I'm not sure if its possible, but it would be SUPER helpful if you guys knew a way to do this without going to the website and clicking the button :)

**Comment by exhaustin** [comment]
As far as I know libfranka does not provide an API for use to do that programmatically, probably for safety reasons. However you can follow instructions in [this](https://facebookresearch.github.io/fairo/polymetis/prereq.html#setting-up-the-franka-panda) section of our docs to set up [FoxyProxy](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/) to forward the webpage to any machine that is ssh'd into the NUC, which has worked quite well for us.

**Comment by AlexanderKhazatsky** [comment]
Oh well, thanks for the reply!
