### ISSUE TITLE
Add Directional Velocity To Gripper State

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1369]
## Type of Issue

Select the type of issue:
- [ X] Feature request (to request an additional feature)

## Description
A really useful feature for learning from demonstrations is directional gripper velocity. This way, the agent can tell if it is opening or closing the gripper from a single state.

It seems that everything is in place to add this currently. Would be very much appreciated!

**Comment by exhaustin** [comment]
The velocity is not part of the gripper state exposed by libfranka (see [franka::GripperState](https://frankaemika.github.io/libfranka/structfranka_1_1GripperState.html)), so there's no raw velocity data we can expose directly.
Can you see if querying the gripper state two times and comparing the results is sufficient for your needs?

**Comment by AlexanderKhazatsky** [comment]
Ah, this surprisingly worked beautifully! Thank you as always :)
