### ISSUE TITLE
Polysim guideline

### ISSUE THREAD

**Issue by HaoLiRobo** [facebookresearch/fairo#1385]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [x] Documentation Ask

## Description

Hi, I'm trying to use polysim to simulate panda arm. I find a few files that might be useful for me, but do not know how to utilize them. Such as bullet_manipulator.py (I find two of them in the polysim env folder). Could you provide more example code on how to use these scripts?

## Current Behavior

I read this [post](https://github.com/facebookresearch/fairo/pull/1237), I run launch_robot with client=none and launch_gripper with gripper=none. Then I run bullet_manipulator in the experimental folder. What shall I do next to control the robot in the pybullet simulatior? 

When I run one of the script in the tests folder such as 0_joint_positions.py, it gives me the error of assert Kx shape is not [6,6], which is [0,0] instead.

Spent a day on it, still cannot get the simulator running. I run the launch_robot.py client=franka_sim. It has a panda arm with no gripper on it. I can run test scripts without gripper like 0_joint_positions.py. When I tried to launch_gripper.py gripper=franka_hand and change the robot ip to localhost, it gives me NetworkException. I think I'm not using the correct yaml file to launch the gripper. I tried to change it, but nothing worked. I would really appreciate it if the guidelines to use the simulation can be more complete and detailed. Thank you for making this great simulator!

## Links to any relevant pastes or documents 

https://github.com/facebookresearch/fairo/pull/1237

**Comment by HaoLiRobo** [comment]
I still cannot successfully run the simulation of a franka with gripper. Did I miss something in the documentation?

**Comment by exhaustin** [comment]
Fixed!
