### ISSUE TITLE
How To Change Franka Limits?

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [facebookresearch/fairo#1389]
Hello, I am aware of two separate safety controllers: 1) the polymetis one, 2) the underlying franka one

I am using the robot to open physical drawers and cabinets, and I keep getting a cartesian_reflex complaint from the underlying franka safety controller.

On their website, they say that if you are working with physical objects this is expected, and the safety value should be raised with some command (see Reflex Errors): https://frankaemika.github.io/docs/libfranka.html

How would I go about changing these values, since I assume all this stuff is wrapped up in polymetis?

Thank you as always!

**Comment by AlexanderKhazatsky** [comment]
Generally, I am running into torque issues when working with hinged objects. This happens even when moving the robot very slowly, but the movement of the robot arm isn’t perfect (Ie. It pushes against the door in a non-giving way). I was wondering you guys have advice for how to address this?

**Comment by exhaustin** [comment]
You can increase these tolerances by increasing the collision behavior values within the config file [here](https://github.com/facebookresearch/fairo/blob/50e18ea63ca8de028479ebed19d43697036d2634/polymetis/polymetis/conf/robot_client/franka_hardware.yaml#L77). If you are installing through conda, you can override the values with `launch_robot.py robot_client=franka_hardware robot_client.executable_cfg.collision_behavior=[......]`

To give your robot more compliance, you can trying tuning down the `Kq_default`, `Kqd_default`, `Kx_default`, and `Kxd_default` values within `RobotInterface`, then re-launching `start_cartesian_impedance`. This will give your robot more compliance, but at the sacrifice of accuracy and will result in different dynamics.

**Comment by AlexanderKhazatsky** [comment]
When I change these values, I seem to get a tau_j_range_violation. When I print out the commanded toques, they don't actually have a magnitude greater than 6, so I'm not sure why it keeps freezing the robot due to range violates... Do you guys happen to have any ideas? I'm currently not able to reliably use the controller to interact with hinged objects
