### ISSUE TITLE
Gripper Force not working

### ISSUE THREAD

**Issue by HaoLiRobo** [facebookresearch/fairo#1397]
## Type of Issue

Select the type of issue:
- [x ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

When I set grip force in the go to function in gripper interface, it doesn't have any effect. The grip force seems to be the same for all numbers I set. Even if I set it to be 0, it still grasp with a large force. My current polymetis version is 636, which is an really old version, but this is the only version that can launch my panda. Could you please tell me what I shall do to change the grip force? Thanks!

**Comment by exhaustin** [comment]
Polymetis merely forwards the force argument to the [libfranka Gripper object](https://frankaemika.github.io/libfranka/classfranka_1_1Gripper.html).
My previous experiences with the Franka Hand has been similar, where the force parameter seems to have no effect on the grip force. 
Can you try using raw libfranka and see if you observe the same thing? If so there's not much we can do on the Polymetis side. If you observe a discrepancy between using Polymetis and directly using libfranka, then please let us know and reopen the issue.
