### ISSUE TITLE
jerky robot motion and sounds

### ISSUE THREAD

**Issue by snasiriany** [facebookresearch/fairo#1411]
## Type of Issue

Select the type of issue:
- [ x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

We are trying polymetis with the Cartesian impedance controller. We are observing jerky behaviors and loud tick-tick sounds coming from (I believe) the third joint of the Franka Panda robot when moving back and forth from left to right. The issue does not arise when moving forward and back.

## Current Behavior

Attaching a video of the behavior with polymetis:

https://user-images.githubusercontent.com/11937650/226426675-9e620053-5f6c-4f81-bd21-c4b4f57f121a.mov

## Expected Behavior

We tried an alternative controller [deoxys](https://ut-austin-rpl.github.io/deoxys-docs/html/getting_started/overview.html) using the operational space controller (OSC), but did not observe the same issues:

https://user-images.githubusercontent.com/11937650/226427257-09f3a614-7820-471a-a4b0-68a0f4bca5bc.MOV

## Steps to reproduce

Can provide additional code if needed!

**Comment by snasiriany** [comment]
has anyone encountered this issue before?

**Comment by exhaustin** [comment]
Controller instability might be caused by 
1. Network latency
2. High gains

If you are not experiencing issues with deoxys on the same network setup, then I would suggest lowering the gains, which can be done by passing in `Kx` and `Kxd` values to [`start_cartesian_impedance`](https://facebookresearch.github.io/fairo/polymetis/polymetis.html#polymetis.robot_interface.RobotInterface.start_cartesian_impedance).
Default values for the gains (which is what the controller uses without explicitly passing gains in) can be found [here](https://github.com/facebookresearch/fairo/blob/0a01a7fa7a7c65b2f9a3aebf5e79040940daf9d2/polymetis/polymetis/conf/robot_client/franka_hardware.yaml#L12).

**Comment by snasiriany** [comment]
Thank you for the suggestion! I tried reduced `Kx` from `[750, 750, 750, 15, 15, 15]` to `[150, 150, 150, 15, 15, 15]` and this substantially reduced the noise coming from the joints. There is still some noise but if I reduce the gains further the control will feel laggy and slow. I did not notice a difference from changing `Kxd`.

For now, I feel that reducing the gains may be more of a bandaid rather than a permanent fix. Are there other things we can try? Perhaps a trajectory interpolator or some form of smoothing can help.

**Comment by exhaustin** [comment]
I wouldn't say that reducing the gains are a band-aid. Every impedance control system has gains that needs to be tuned and the optimal set of gains depend on the usecase and the dynamics of your exact system, including network and computation latency. Tuning the gains to fit your need is the most straightforward way of resolving this issue.

If it is physically impossible to achieve desired performance with any set of gains, then it may be that the control latency might be too large. That's when I would start looking into improving CPU and network performance.

Smoothing the trajectory most likely not going to help as the instability is coming from the feedback and not the reference. Having the trajectory move slower might help, though.

It is worth noting that Polymetis sacrifices control latency for flexibility in being able to send arbitrary low-level controllers on the fly, so is more prone to being unstable in the case of a slower CPU, slower network, or dynamic model inaccuracies.

**Comment by snasiriany** [comment]
Thank you for providing this detailed insight! I will take these tips into consideration and contact you if I need additional assistance. I will close the issue for now.
