### ISSUE TITLE
Remove dependency conflicts in `requirements.txt`

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/fairo#37]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

## Description

There are dependency conflicts in our requirements, and packages frozen on old versions.
This is affecting our env setup and will be a pain point for new users.

## Current Behavior

Example of error from pip install:
```
(droidlet_test_env) [~/droidlet]$ pip install mypy-extensions==0.4.1             *[rebeccaqian_inference_script_fix]

Looking in indexes: https://pypi.org/simple, http://100.97.64.150
Collecting mypy-extensions==0.4.1
  Using cached mypy_extensions-0.4.1-py2.py3-none-any.whl (3.6 kB)
Installing collected packages: mypy-extensions
  Attempting uninstall: mypy-extensions
    Found existing installation: mypy-extensions 0.4.3
    Uninstalling mypy-extensions-0.4.3:
      Successfully uninstalled mypy-extensions-0.4.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mypy 0.800 requires mypy-extensions<0.5.0,>=0.4.3, but you have mypy-extensions 0.4.1 which is incompatible.
Successfully installed mypy-extensions-0.4.1
```

## Expected Behavior

A new user should be able to create a new env and install requirements relatively smoothly. This is something that we will need to maintain regularly.  

## Steps to reproduce

```
conda create --name [NEW_ENV]
conda activate [NEW_ENV]
pip install -r requirements.txt
```

**Comment by kavyasrinet** [comment]
Thanks for creating the issue. Which anaconda module are you using ?

**Comment by kavyasrinet** [comment]
@snyxan can you take this one ?

**Comment by kavyasrinet** [comment]
Checking here again if this is still an issue @Rebecca-Qian , @snyxan
