### ISSUE TITLE
running craftassist, building the client and the server

### ISSUE THREAD

**Issue by bycloudai** [facebookresearch/fairo#46]
Hello,
It seems that I am kind of here too early.
I am just wondering is it currently possible to run the craftassist locally right now?
The step where it says:
![image](https://user-images.githubusercontent.com/29135514/106278812-52380c80-6276-11eb-92f1-c6006906f8b4.png)
"make"

What should I do exactly here?
If it is coming up shortly in the next few commits I'll just be back again. 
If I can run this successfully on my PC locally, I'll be making a video tutorial of how to install it for others too.

Thank you guys for the amazing work!

**Comment by snyxan** [comment]
Hi @cloudweather, thanks for the issue!

Could you post the error you got?

**Comment by cloudweather** [comment]
This is my current error after I ran the command 
```
python ./agent/craftassist_agent.py
```

![Screenshot 2021-01-30 035335](https://user-images.githubusercontent.com/29135514/106321099-cababf80-62ae-11eb-9db4-b4f45505f73f.png)

**Comment by snyxan** [comment]
You will have to compile mc_agent before running `python ./agent/craftassist_agent.py`. Try it from root:

```
cd craftassist
make
```

If you already did so but didn't compile it successfully, please kindly post the corresponding error here.

**Comment by cloudweather** [comment]
Sorry! I didn't realize `make` is for Linux system, I am currently running on a Windows system that's why it's not working.
Is there any way that I can run it on Windows?

**Comment by snyxan** [comment]
Currently Windows installation is not supported (and not in near future). In your case, we recommend use docker installation or Linux virtual machine.

**Comment by cloudweather** [comment]
ok, I am now testing it on WSL. I've been manually installing the libraries, but I got stuck finding the library for this one:

![image](https://user-images.githubusercontent.com/29135514/106395125-801a7e00-643b-11eb-861e-e9b688c8452b.png)

where can I find it?

**Comment by snyxan** [comment]
The error is from submodule cuberite. It's not supposed to happen if you successfully initialized this submodule.

The following command might be helpful:

```
git submodule update --init --recursive
git submodule update --recursive
```

**Comment by cloudweather** [comment]
Sorry, I might be going around in a circle here, but I am now trying it on WSL and trying to install it through docker.

```
./tools/docker/local_install.sh
```
I have made a docker account and signed in too. But this command still gives me this error.

![image](https://user-images.githubusercontent.com/29135514/106503827-1cf31f00-6501-11eb-9c37-c0bab6275fa1.png)

Thank you for your patience

**Comment by billagee** [comment]
@cloudweather At the risk of sending you back to an approach you've already tried, I would suggest returning to building in an 18.04 WSL environment without Docker - I was able to get craftassist running that way recently. This has Docker-like benefits since it's pretty easy to destroy and rebuild your 18.04 WSL env if something goes wrong.

Note that I was using WSL 2 - note sure what the results will be in WSL 1.

Another important note is that I went through the install steps in the Cuda on WSL guide before trying to set up the craftassist env:

  https://docs.nvidia.com/cuda/wsl-user-guide/index.html

Without Cuda on WSL, I'm not sure what the results will be. From what I can tell, it still requires that you switch the OS to the Windows Fast ring and get a recent Windows build.

In case it's helpful, here are the rest of my WSL setup steps:

```
1. Start an 18.04 WSL shell and clone droidlet:

git clone --depth=1 --recursive https://github.com/facebookresearch/droidlet.git

cd droidlet


2. In the same 18.04 shell, install miniconda, then create and activate a 3.7 conda env named "droidlet_env":

# See https://docs.anaconda.com/anaconda/install/silent-mode/

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh

bash ~/miniconda.sh -b -p $HOME/miniconda

eval "$(~/miniconda/bin/conda shell.bash hook)"

conda init

conda create -n droidlet_env python==3.7

conda activate droidlet_env


3. Install apt packages and Python dependencies:

sudo apt update && \
  sudo apt install -y libfreetype6-dev build-essential cmake libgoogle-glog-dev libeigen3-dev libboost-all-dev

pip install -r requirements.txt

pip install -r craftassist/requirements.txt


4. Build craftassist (local installation)

# From:
# https://github.com/facebookresearch/droidlet/blob/main/craftassist/README.md#option-b-local-installation

cd craftassist
make


5. Launch cuberite

python cuberite_process.py --config flat_world 


6. In another shell, launch the agent

python ./agent/craftassist_agent.py


7. On WSL 2, to connect a Minecraft client on your host machine the cuberite server running in WSL, you'll need to run a `portproxy add` command on the Windows host. To do that:   
 
- Run `ifconfig eth0` in your 18.04 VM to get the IP the cuberite server is listening on

- Outside of WSL, open an Administrator powershell session, and add the port proxy:

    # e.g., for IP 172.24.45.2:
    netsh interface portproxy add v4tov4 listenport=25565 listenaddress=0.0.0.0 connectport=25565 connectaddress=172.24.45.2

    # See also:
    # https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-a-wsl-2-distribution-from-your-local-area-network-lan
```

**Comment by cloudweather** [comment]
@billagee Thank you so much for your detailed instructions. I was able to get to step 6 until I was greeted with this error:

![image](https://user-images.githubusercontent.com/29135514/107419031-4986e680-6b52-11eb-89db-9222fd45697e.png)

However, I can join the server. 

Did I not "make" successfully?

**Comment by billagee** [comment]
@bycloudai I tried doing a clean build with the latest droidlet main commit as of today (1524c24) and was able to run the agent successfully ... 

I noticed the error you hit was in this part of the code:
```
from spacy.lang.en import English
from typing import List

tokenizer = English().Defaults.create_tokenizer()
```
I'm curious what the native language/locale of your Windows machine is? Perhaps there's a spacy (or Windows or Ubuntu/WSL) issue related to that. Here's some output from my Win 10 machine (from running `dism` in powershell) showing my settings:

```
PS C:\WINDOWS\system32> dism /online /get-intl
...
Default system UI language : en-US
System locale : en-US
...
Installed language(s): en-US
```
And in my 18.04 WSL VM:
```
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
# (all other LC_ values are also set to "C.UTF-8")
```

**Comment by bycloudai** [comment]
@billagee hey thanks for your reply again!
I just checked my system with the commands you ran on yours too and here are the results:

powershell
```
PS C:\WINDOWS\system32> dism /online /get-intl
...
Default system UI language : en-US
System locale : en-US
...
Installed language(s): en-US
  Type : Fully localized language.
Installed language(s): zh-TW
  Type : Partially localized language, MUI type.
  Fallback Languages en-US
```
18.04 WSL VM
```
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
# (all other LC_ values are also set to "C.UTF-8")
...
LC_ALL=
```

I also just rebuilt the whole thing with the latest commit, it seems that it is still receiving the same error. Is this some sort of default language system problem? I use 2 languages on my system btw.

**Comment by billagee** [comment]
@bycloudai Yeah, it sounds like the system language is something worth investigating...I'm not familiar with spaCy, so I'm not sure if there's a simple solution I'm overlooking.

Does the issue repro if you launch python in interactive mode in the droidlet_env conda env and run the `tokenizer = English().Defaults.create_tokenizer()` line as shown below?
```
(droidlet_env) $ python

>>> from spacy.lang.en import English
>>> tokenizer = English().Defaults.create_tokenizer()
```

**Comment by bycloudai** [comment]
This is before installing 
![image](https://user-images.githubusercontent.com/29135514/110334683-fd9a6500-805d-11eb-95c2-9be0c24618e6.png)

This is after installing `python -m spacy download en_core_web_sm`
![image](https://user-images.githubusercontent.com/29135514/110335327-acd73c00-805e-11eb-9d3f-afcd38a13efa.png)

it still gives the same error:/

**Comment by billagee** [comment]
@bycloudai I see...since it seems to be a spaCy issue, they might be able to offer some hints on what to try, over in their issues page: ttps://github.com/explosion/spaCy/issues

If you file an issue there feel free to @ mention me, since I'm curious to see what they think  👍 

I also found this doc, which ad the interesting info: `WSL install will try to automatically change the Ubuntu locale to match the locale of your Windows install.`

https://docs.microsoft.com/en-us/windows/wsl/troubleshooting#changing-the-display-language

That doc suggests running `sudo update-locale LANG=en_US.UTF8` to switch the Ubuntu locale to en-US, and opening a new terminal where the change will have taken effect...not sure if the display language has anything to do with spaCy's behavior, but I wonder if making that change and then re-creating the conda env (including the spaCy installation) would help?

**Comment by bycloudai** [comment]
Hi, I just opened an [issue ](https://github.com/explosion/spaCy/issues/7397) over there. 
I've tried the `sudo update-locale LANG=en_US.UTF8` and it still didn't work. 
Thank you for your assistance btw.
