### ISSUE TITLE
Models and dataset refactor proposal

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/fairo#734]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
We need to design our models and datasets folders so we can host Zoos of models/datasets under a common structure that all supported agents can use (compared to having these folders under agent specific directories like : `craftassist/agent/models` or `locobot/agent/datasets`).

### Current state
Right now the datasets and models reside inside the respective agents folders:
- `agents/craftassist/datasets/` - only has nsp dataset
- `agents/craftassist/models`:
  - `agents/craftassist/models/perception`
  - `agents/craftassist/models/semantic_parser`

- `agents/locobot/datasets` - only has nsp dataset
- `agents/locobot/models`:
  - `agents/locobot/models/perception`
  - `agents/locobot/models/semantic_parser/`

## Proposal
Models and datasets are part of the library:

- `droidlet/artifacts/models`
- `droidlet/artifacts/datasets`:
  - `droidlet/artifacts/datasets/nlu`
  -  `droidlet/artifacts/datasets/perception`
    - `droidlet/artifacts/datasets/perception/robot`
      - ... all robot datasets go here (with documentation of format)
    - `droidlet/artifacts/datasets/perception/craftassist`
      - ..  all craftassist datasets go here
  - `droidlet/artifacts/datasets/human_robot_interface`: Annotations that come directly from dashaboard - for example from vision annotation tool and 
    - `droidlet/artifacts/datasets/human_robot_interface/nlu`
    - `droidlet/artifacts/datasets/human_robot_interface/vision`
    - `droidlet/artifacts/datasets/human_robot_interface/memory`
    - `droidlet/artifacts/datasets/human_robot_interface/blocky_programming`

We also add usage for our models and datasets in documentation like : https://pytorch.org/hub/facebookresearch_pytorchvideo_resnet/

Nit to double check : The only difference between the two datasets directories is additional files: datasets_checksum.txt and checksum.txt in craftassist. Do we need these at all with the new setup ?

**Comment by kavyasrinet** [comment]
Craftassist perception model tracking needs to be fixed. Issue here: https://github.com/facebookresearch/fairo/issues/735

**Comment by stuart-fb** [comment]
I like this change.  Now that multiple agents can depend on the same model, how will we handle model version changes?

It seems to me there are cases where you want to pin a dependency to a particular model version, and cases where you want to ensure that two agents are always using the same version, while allowing the particular version to float as the model is updated.  Perhaps there's already a standard way this gets handled?

**Comment by kavyasrinet** [comment]
> I like this change. Now that multiple agents can depend on the same model, how will we handle model version changes?
> 
> It seems to me there are cases where you want to pin a dependency to a particular model version, and cases where you want to ensure that two agents are always using the same version, while allowing the particular version to float as the model is updated. Perhaps there's already a standard way this gets handled?

Yeah this is a great point - we can aim to keep supporting the last 5 versions of the artifacts on S3 - where they will be stored. 
We have some bash scripts in place that track and match model/dataset versions based on shahash of the respective folders right now. Currently, the agents trigger a model/dataset download on start if their local hash differs from what's checked in on main - we could leverage and expand on this to support versioning and tying versions to agents.

**Comment by kavyasrinet** [comment]
> I don't understand, is data duplicated? or split... like in droidlet/artifacts/datasets/perception/robot and droidlet/artifacts/datasets/human_robot_interface/vision ?

This is up for discussion - I was thinking whether we should support dashboard artifacts somewhere. I know Hollis' tool collects annotation in place right now and lets you retrain a new model (which will result into new model and data files) from dashboard.
