### ISSUE TITLE
can't connect Minecraft game client

### ISSUE THREAD

**Issue by SNUFEC** [facebookresearch/fairo#744]
## Description

I've installed craftassist via docker and moved on the 'run cuberite' part and 'connecting to the minecraft client'. 
However, I kept failing on direct connecting the server 'localhost:25565'. 
It keeps showing me an error message that says, connection refused.
(The screenshot 1 attached below)
<img width="428" alt="접속에러" src="https://user-images.githubusercontent.com/91736347/136993637-6143cbed-bebf-4ae9-8cf2-609934907def.png">

## Current Behavior

I have three questions.

1. Does the screenshot 2 below seem proper? 
<img width="459" alt="cuberite 엔딩 부분" src="https://user-images.githubusercontent.com/91736347/137114649-4bada5a9-00d0-4466-aa90-6bcbdb0f0db2.png">

(ignore the 's' at the end. i made a typo during screenshot)

The screenshot 2 above is what i got after i typed in "python droidlet/lowlevel/minecraft/cuberite_process.py --config flat_world" in the running docker container. 
It's the last step of 'running cuberite instance' in the craftassist READ.ME.(https://github.com/facebookresearch/fairo/blob/main/agents/craftassist/README.md)

2. Is it right to run both the game and the cuberite instance at the sametime? 
I left the cuberite run (didn't exit the terminal) and logged into the minecraft game.
I set the version to 1.12, and 'mutiplayer' > 'direct connect' > typed in 'localhost:25565'.
Then it shows 'io.netty~~~ connection refused' error.

3. What could be the cause of the error 'io.netty. ~~~ connection refused'?
I've tried port forwarding, changing the ip adress,  updating java, and fire wall issues. Nothing worked.
By the way, I could direct connect other servers, so I don't think it's the problem of firewall or port forwarding. 
 

## Expected Behavior

What should i do to connect the client to the running Cuberite instance? 
Do I need any extra actions which are not listed in READ.ME?
For example, compiling something or installing any extra software?

## Steps to reproduce

I've attached the log file i've done so far. 
[깃헙에 물어볼 내용.txt](https://github.com/facebookresearch/fairo/files/7336224/default.txt)

## Links to any relevant pastes or documents 

https://10scopes.com/fix-io-netty-channel-abstractchannelannotatedconnectexception/
I've found this blog, and I wonder if I should have made a 'Minecraft server > Maxwell', just as number 3 in the post says.

![image](https://user-images.githubusercontent.com/91736347/136988433-26134339-cf70-4b56-8d8f-19a29add0347.png)

**Comment by snyxan** [comment]
For question#3:

I need some more details to answer your question -- it seems that you are running cuberite and agent in the docker container and minecraft game client on your local machine, usually what you need to do is to tunnel port 25565 so that the your connection to localhost:25565 can be forwarded to the same port of the docker container, thus your local minecraft game client can connect to the cuberite server hosted in that docker container.

**Comment by kavyasrinet** [comment]
Thanks for picking this up @snyxan.

> I took a look at the log file you attached, seems that you are running docker container without tunneling the port 25565. Could you try something like `docker run -it -p 25565:25565 -p 3000:3000 -p 2556:2556 -p 2557:2557 -p 9000:9000 -p 5000:5000 -p 8000:8000 --name droidlet_container droidlet` to start the container? We use the same command in the [local install script](https://github.com/facebookresearch/fairo/blob/main/tools/docker/local_install.sh)


Yes the solution proposed above should solve it.

**Comment by SNUFEC** [comment]
Thanks a lot!!! It worked!! 

> I took a look at the log file you attached, seems that you are running docker container without tunneling the port 25565. Could you try something like `docker run -it -p 25565:25565 -p 3000:3000 -p 2556:2556 -p 2557:2557 -p 9000:9000 -p 5000:5000 -p 8000:8000 --name droidlet_container droidlet` to start the container? We use the same command in the [local install script](https://github.com/facebookresearch/fairo/blob/main/tools/docker/local_install.sh)

Now I can interact with the agent smoothly but I have one last question. 
During the interaction with the agent, I sometimes get this Type error below. What could be the cause? 
<img width="459" alt="에이전트날아가는에러" src="https://user-images.githubusercontent.com/91736347/137245574-91a9e211-3698-4ba7-9869-8c697e5d3d71.png">

Is it because i made him do something that he doesn't understand? 
I only asked him to point at an object named 'torch'.
[깃헙에 물어보기 2 에이전트.txt](https://github.com/facebookresearch/fairo/files/7342763/2.txt)

**Comment by snyxan** [comment]
It's a recently introduced bug (#731). we are fixing it.

**Comment by SNUFEC** [comment]
Oh I see. Then I'll close the issue here.
Thanks for the replies! 

> > Thanks a lot!!! It worked!!
> > > I took a look at the log file you attached, seems that you are running docker container without tunneling the port 25565. Could you try something like `docker run -it -p 25565:25565 -p 3000:3000 -p 2556:2556 -p 2557:2557 -p 9000:9000 -p 5000:5000 -p 8000:8000 --name droidlet_container droidlet` to start the container? We use the same command in the [local install script](https://github.com/facebookresearch/fairo/blob/main/tools/docker/local_install.sh)
> > 
> > 
> > Now I can interact with the agent smoothly but I have one last question. During the interaction with the agent, I sometimes get this Type error below. What could be the cause? <img alt="에이전트날아가는에러" width="459" src="https://user-images.githubusercontent.com/91736347/137245574-91a9e211-3698-4ba7-9869-8c697e5d3d71.png">
> > Is it because i made him do something that he doesn't understand? I only asked him to point at an object named 'torch'. [깃헙에 물어보기 2 에이전트.txt](https://github.com/facebookresearch/fairo/files/7342763/2.txt)
> 
> Glad to hear it works now!
> 
> The above error is caused by a recently introduced bug (#731). we are fixing it.
