### ISSUE TITLE
Unknown reference object causes crash and infinite loop

### ISSUE THREAD

**Issue by ethan-carlson** [facebookresearch/fairo#849]
## Type of Issue

Select the type of issue:
- [X] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

When some commands are issued containing a referent that the agent doesn't recognize, it fails, crashes, and can't seem to recover.

## Expected Behavior

When the agent doesn't understand a referent it should ideally be able to report so without crashing, and if it does crash it should do so gracefully without looping infinitely.

## Steps to reproduce

Some examples of commands that cause the crash are in [this spreadsheet](https://docs.google.com/spreadsheets/d/1XB9ipSbMhDT34DGKSyz19FGMW-WUWEYbZuR3M2gwsYA/edit#gid=0).  They're all similar.

**Comment by kavyasrinet** [comment]
@aszlam can we prioritize fixing this ?

**Comment by aszlam** [comment]
closed in https://github.com/facebookresearch/fairo/pull/850
