### ISSUE TITLE
[fbrp] IFTTT

### ISSUE THREAD

**Issue by lshamis** [facebookresearch/fairo#876]
Provide tooling or examples of how to trigger IFTTT.

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

**Comment by aszlam** [comment]
if IFTTT is meant to be if this then that programming, we expect to have a decent amount of support for this on the droidlet agent/grammar/NLU side in the next few weeks.  we also have a dashboard tool from a while back that could offer a GUI.  what use case are you considering?
